### ISSUE TITLE
Unable to place blocks while looking at fences/walls

### ISSUE THREAD

**Issue by kawaiicakes** [lilypuree/ConnectibleChains#20] opened 2023-07-26 13:54 UTC
Minecraft 1.19.2
Forge 43.2.14
Connectible Chains 1.0.0

Any attempt to place a block while aiming at a fence fails. #19 appears to be this exact bug. Attached is relevant output from the dedicated server console.

[connectible chains dedicated server log.txt](https://github.com/lilypuree/ConnectibleChains/files/12173313/connectible.chains.dedicated.server.log.txt)

**Comment by SiverDX** [comment] 2023-07-29 09:40
https://github.com/lilypuree/ConnectibleChains/blob/8a966dfdf7263162aff1a546534a0721c3571937/src/main/java/com/lilypuree/connectiblechains/ConnectibleChains.java#L113

is the cause
crouching works because the method exits early if the player is crouching

https://github.com/lilypuree/ConnectibleChains/pull/16 doesn't have this problem

**Comment by Mysticpasta1** [comment] 2023-08-03 12:29
fixed in newest version

**Closed as completed by Mysticpasta1** 2023-08-03 12:29 UTC
